# Generated by Django 3.2.6 on 2021-09-08 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='address_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the addresss name', max_length=200)),
                ('location_country', models.CharField(blank=True, help_text='Enter the country', max_length=200, null=True)),
                ('location_locality', models.CharField(blank=True, help_text='Enter the locality', max_length=200, null=True)),
                ('location_city', models.CharField(blank=True, help_text='Enter the city', max_length=2000, null=True)),
                ('location_zipcode', models.CharField(blank=True, help_text='Enter the citys ZIP code', max_length=20, null=True)),
                ('location_address_line_1', models.TextField(blank=True, help_text='Enter address "line 1"', max_length=1000, null=True)),
                ('location_address_line_2', models.TextField(blank=True, help_text='Enter address "line 2"', max_length=1000, null=True)),
            ],
            options={
                'permissions': (('can_create_address', 'Create new address objects'), ('can_update_address', 'Update existing address objects'), ('can_delete_address', 'Delete existing address objects')),
            },
        ),
        migrations.AlterModelOptions(
            name='site_type',
            options={'permissions': (('can_create_site', 'Create new Site objects'), ('can_update_site', 'Update existing Site objects'), ('can_delete_site', 'Delete existing Site objects'))},
        ),
        migrations.RemoveField(
            model_name='acquisition_location',
            name='acquisition_location_address_line_1',
        ),
        migrations.RemoveField(
            model_name='acquisition_location',
            name='acquisition_location_address_line_2',
        ),
        migrations.RemoveField(
            model_name='acquisition_location',
            name='acquisition_location_city',
        ),
        migrations.RemoveField(
            model_name='acquisition_location',
            name='acquisition_location_country',
        ),
        migrations.RemoveField(
            model_name='acquisition_location',
            name='acquisition_location_locality',
        ),
        migrations.RemoveField(
            model_name='acquisition_location',
            name='acquisition_location_url',
        ),
        migrations.RemoveField(
            model_name='manufacturer_type',
            name='location_address_line_1',
        ),
        migrations.RemoveField(
            model_name='manufacturer_type',
            name='location_address_line_2',
        ),
        migrations.RemoveField(
            model_name='manufacturer_type',
            name='location_city',
        ),
        migrations.RemoveField(
            model_name='manufacturer_type',
            name='location_country',
        ),
        migrations.RemoveField(
            model_name='manufacturer_type',
            name='location_locality',
        ),
        migrations.RemoveField(
            model_name='manufacturer_type',
            name='location_url',
        ),
        migrations.RemoveField(
            model_name='site_type',
            name='site_location_address_line_1',
        ),
        migrations.RemoveField(
            model_name='site_type',
            name='site_location_address_line_2',
        ),
        migrations.RemoveField(
            model_name='site_type',
            name='site_location_city',
        ),
        migrations.RemoveField(
            model_name='site_type',
            name='site_location_country',
        ),
        migrations.RemoveField(
            model_name='site_type',
            name='site_location_locality',
        ),
        migrations.RemoveField(
            model_name='site_type',
            name='site_location_url',
        ),
        migrations.AddField(
            model_name='acquisition_location',
            name='acquisition_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address_type'),
        ),
        migrations.AddField(
            model_name='manufacturer_type',
            name='manufacturer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address_type'),
        ),
        migrations.AddField(
            model_name='site_type',
            name='site_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address_type'),
        ),
    ]
