# Generated by Django 3.2.6 on 2021-09-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210908_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition_location',
            name='name',
            field=models.CharField(help_text='Enter the acquisition locations name (E.g. Albertsons, Costco, manufacturer direct, etc.)', max_length=200),
        ),
        migrations.AlterField(
            model_name='container_type',
            name='name',
            field=models.CharField(help_text='Enter the container type (E.g. refrigerator, pantry, etc.)', max_length=200),
        ),
        migrations.AlterField(
            model_name='item_type',
            name='name',
            field=models.CharField(help_text='Enter the item type (E.g. new york steak, captain crunch, etc.)', max_length=200),
        ),
        migrations.AlterField(
            model_name='manufacturer_type',
            name='name',
            field=models.CharField(help_text='Enter the manufacturers name (E.g. Samsung, LG, home-made, etc.)', max_length=200),
        ),
        migrations.AlterField(
            model_name='site_type',
            name='name',
            field=models.CharField(help_text='Enter the sites name (E.g. home, LG, guest house, etc.)', max_length=200),
        ),
    ]
