# Generated by Django 3.2.6 on 2021-09-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_registration_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_object_instance',
            options={'ordering': ['container_instance', 'item'], 'permissions': (('can_create_item_object_instance', 'Create new item object instances'), ('can_update_item_object_instance', 'Update existing item object instances'), ('can_delete_item_object_instance', 'Delete existing item object instances'))},
        ),
    ]
