# Generated by Django 3.2.6 on 2021-09-16 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0010_alter_container_object_instance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the container type (E.g. refrigerator, pantry, etc.)', max_length=200)),
                ('custom_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='auth.group')),
            ],
        ),
    ]
