# Generated by Django 3.2.6 on 2021-09-16 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_group_roster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_roster',
            name='name',
        ),
    ]
